### ISSUE TITLE
Gemfile.lockの更新

### ISSUE THREAD

**Issue by uribo** [tokyor/r3#13]
警告が出ている

**Comment by yutannihilation** [comment]
これあんま理解できてないんですが、Gemfile.lockってコミットする必要なかったりしない？

**Comment by uribo** [comment]
私もよくわかっていないのですが、週末調べてやるつもりです。

**Comment by yutannihilation** [comment]
了解です。まあこのレポジトリは警告は無視していいと思いますよ。悪意ある攻撃者からのPRをローカルのJekyllでプレビューすると何か起こる可能性はあるけど、あんまり考えられないシナリオかなと。

**Comment by uribo** [comment]
ありがとうございます。よくわかっておらず...

> Gemfile.lockってコミットする必要なかったりしない？

これは、そもそもGemfile.lockファイルをignoreしていても良いのでは、という話でしょうか

**Comment by yutannihilation** [comment]
ですです。Gemfile.lockがなければその時点での最新になるはずで、しかも肝心のGitHub PagesはGemfile.lockのバージョン指定に関係なく動いているわけなので、lockでバージョンを固定するのはあんまり意味ないかなあと。

**Comment by uribo** [comment]
なるほどなるほど。Gemfile.lockの役割を勘違いをしておりました、すみません。
（結局ちょっと調べた）

お手数でなければ Gemfile.lock をignoreに追加していただけますか

**Comment by yutannihilation** [comment]
ではやっちゃいます！ なんか表示が変になったりしたら戻そう。

**Comment by yutannihilation** [comment]
やったか...？

**Comment by uribo** [comment]
お、警告が消えた！あざます🙌あざます🙌
サイトの方も見た目問題ないですね！GJ!!

**Comment by yutannihilation** [comment]
👍
