### ISSUE TITLE
Rラジオ忘年会2017

### ISSUE THREAD

**Issue by uribo** [tokyor/r3#20]
![r3bounen](https://user-images.githubusercontent.com/228649/34277525-7de86e30-e6e9-11e7-8978-6fe476f43346.png)

自由参加形式（Discordでの収録）で今年のR活動などを話題に雑談（予定）

# 内容

- 今年の振り返り (KPT)
- 来年の目標 (Rに限らず)
- このパッケージがすごい2017 (おすすめパッケージの紹介)
- 俺に語らせろのコーナー
- ...

# 時間

昼の部

13:00 - 15:00 (2hのうちの適当なタイミング)

夜の部

21:00 - 23:00 (2hのうちの適当なタイミング)

# 備考

希望者の方には昼の部のみ、つくば市内の 🏠 @uribo 部屋を解放します。
収録したり💪進捗を出したり、🎥映画をみたり、🍕ピザ食べたり、基本的に自由に過ごしていただけるようにします。
詳細は @uriboまで (📨TwitterのDM等 id: u_ribo へどうぞ)

**Comment by yutannihilation** [comment]
ｳﾘﾎﾞｰ部屋は定員何名なんでしょう？

**Comment by uribo** [comment]
4~7人くらいですかね
