### ISSUE TITLE
ぞうさん回

### ISSUE THREAD

**Issue by uribo** [tokyor/r3#6]
ぞうさんこと@kazutan と @uribo が話します。

## 内容 (予定)

- 自己紹介
- ぞうさんのRとの出会い、ぞうさん通信
- Hijiyama.R (zousan.R)
    - [\#final](https://atnd.org/events/90406) 20171126 
- 教えてぞうさん出張版 (Twitter, Ask.fm, リアルタイムでの質問コーナー)
    - \#ありがとうぞうさん... slack, twitter
        - https://twitter.com/simizu706/status/925182708963205120
    - \#ビールうめぇ
- 犬4匹本
- 仕事とRと...
- rmarkdownへのこだわり
    - *blogdown*, *bookdown*
- R界隈ニュース
    - Rラジオの反響
    - Japan.R 一般参加の募集が始まった https://japanr.connpass.com/event/70230/ キャンセルも出るのでは? 要登録
    - RProjectの履歴足りない問題。みんなはいくつRStudioを立ち上げている?
        - ref) https://twitter.com/hoxo_m/status/922765232140722176
    - おすすめ・気になるパッケージ📦
        - medium流行ってんの?  ([*mediumr*](https://github.com/yutannihilation/mediumr))
        - [*icon*](https://github.com/ropenscilabs/icon)... font awesome等のwebアイコンを気軽にRMarkdownへ挿入
        - [*searcher*](https://github.com/coatless/searcher)... エラーメッセージの検索を直接Rから。GitHub検索にも対応。

**Comment by kazutan** [comment]
そうですね…時間次第では仕事関連の優先順位を下げてもらえると助かります。
あと、お便りコーナーじゃないですけど、リスナーからの質問コーナー枠は作ってもらえると嬉しいです。
それ以外は大丈夫です!

**Comment by yutannihilation** [comment]
質問集めるのどうするのがいいんでしょうね。 Twitter上でやるのがお手軽な気がしますが、

* 公式アカウントを作って「ゲストへの質問募集」のツイートにリプライをもらう
* 「#Rラジオ」に加えて「#ゲストへの質問」みたいなタグをつけてツイートしてもらう

とかでしょうか。なんだかんだやっぱり公式アカウントあった方が便利？

**Comment by uribo** [comment]
@yutannihilation 広報も兼ねて公式アカウントかなと思いました。また、録音時に、質問あったら本人まで〜的な発言を公式アカウントでしておいて、質問はゲスト宛とか。

時間的に答えられなかった質問は別途テキストでまとめるとかしたいかな。

引き続き、別途こちらで議論お願いします #8
